### ISSUE TITLE
[Feature] Auto Solver

### ISSUE THREAD

**Issue by Andrew1431** [atlesque/starfield-digipick-solver#1]
Using this to track my work on the auto-solver!

Implementation Notes:
 - The keys are static: they are from a small set of pre-configured keys.
   - I will create a list of all the keys, and you'll be able to choose from them quickly in succession across all (up to 12) keys.
   - I will create another key component that is the actual puzzle with interactive disabling of key prongs (to configure the puzzle)
   - Will then write a recursion formula to test all key combinations! Probably the hardest part :P 
 - Maybe we could then add a feature to generate our own puzzles for fun? :)

**Comment by Andrew1431** [comment]
https://github.com/atlesque/starfield-digipick-solver/assets/9736372/f8c0614d-240d-4e2f-ba26-0a5c15fa54c6

pretty neat so far! done using just raw canvas stuffs.

```typescript
  const draw = useCallback(() => {
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const x = canvas.width / 2;
    const y = canvas.height / 2;
    const radius = canvas.height / 2 - 10;
    const PI = Math.PI;
    const origin = -0.5 * PI;
    const prongOffsetSize = 2 * PI / MAX_PRONGS;
    const prongWidth = 0.06;
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    ctx.lineWidth = 7;

    // 1-32
    for (let i = 1; i <= MAX_PRONGS; i++) {
      const offset = (i - 1) * prongOffsetSize;
      if (prongMap.has(i)) {
        ctx.strokeStyle = "white";
      } else {
        ctx.strokeStyle = "#373a3a";
      }
      ctx.beginPath();
      ctx.arc(x, y, radius, origin - prongWidth + offset, origin + prongWidth + offset);
      ctx.stroke();
    }
  }, [canvas, prongMap]);
  ```

**Comment by atlesque** [comment]
Welcome Andrew! Pleasure having you on board! 🙌

Nice start on the canvas code! If you like, we can brainstorm together about how to handle both input and output.

Here's what I got:

![image](https://github.com/atlesque/starfield-digipick-solver/assets/44317804/e844c409-6e28-43fe-894f-7e3593a00666)


Input:
- Difficulty: determines available keys and layer count
- Keyholes per layer
- Available keys

Biggest challenge I see is how to input the keyhole and key variations.

Ideas:
- Make a step-by-step wizard, starting with first layer
- Input can be done by dragging from the center of the circle to the outer edge. This will draw a line beginning at center and ending somewhere in the circle's ring
- Same for the keys

Output:
- Keys in order of input, with a sequence number (or none if unused)

e.g.

![image](https://github.com/atlesque/starfield-digipick-solver/assets/44317804/990e7272-d6d5-4941-b6b8-6eb756a22ece)

Downside with this output format is it's not sequential, so need to constantly scan for the next value - not great UX.

Improvement ideas for output:
- Highlight keys step-by-step, in order of usage. User can step through next/previous key to use
- Highlight all keys per layer, like we already do with the LAYER option

**Comment by Andrew1431** [comment]
Thanks for the comments! I'm just rushing through this at the moment:

![image](https://github.com/atlesque/starfield-digipick-solver/assets/9736372/13dd0b03-8241-44d8-90cf-393836a09ac3)

Will do a UI pass as it gets closer to release.

I'll show you how I do the inputs in a moment! It's pretty awesome but needs UI/UX love of course.

**Comment by Andrew1431** [comment]
https://github.com/atlesque/starfield-digipick-solver/assets/9736372/d96ff6e9-3eda-42d6-a51d-94f5c9577bd7

alright i'm off for the evening, this was super fun lol can't wait to get back to more of it :)

**Comment by atlesque** [comment]
Looking great!! You're on 🔥 

Am I understanding correctly that there are only a fixed amount of possible key configs (prongs)?

So instead of having to manually input the prongs, you can just select from a list of predefined ones?

Because if yes, that'd make things much easier for input!

Keep up the great work!

**Comment by Andrew1431** [comment]
https://github.com/atlesque/starfield-digipick-solver/assets/9736372/a36e1959-3e5a-4ebb-a506-e634a1f8a4b8

now for the hard part, it's solving time!!

**Comment by Andrew1431** [comment]
Do you care if I add firebase analytics? I can add you as an admin to the firebase console. Not sure if you've ever used firebase!

**Comment by Andrew1431** [comment]
https://github.com/atlesque/starfield-digipick-solver/assets/9736372/0261070a-3112-4c3c-a2b8-2be656b4a9a3

Check it out!!!! This is amazing.

Cleaning up the PR now, for final review.

**Comment by Andrew1431** [comment]
Brutal, I guess I will need to add a custom key builder, most keys match a specific pattern, but there is SOME keys that are coming out as apparently random :( 

Got a nifty solution though that should make this quite simple!

**Comment by Andrew1431** [comment]
Going to make a wizard that generates your keys dynamically, and all you have to do is answer 2 questions, it'll be awesome, and super fast!

**Comment by Andrew1431** [comment]
RIP, refactoring now to be super fast and only 2 clicks on a small screen away from always finding your key

**Comment by Andrew1431** [comment]
Done! lol it's brutal :P might still need to revisit how to enter your keys at some point it's a bit slow. 

Also the master level locks take a good second of bruteforcing, that algorithm needs some serious optimization.

I tested it out in game, and: `Iterations:  23046` it had 23k invocations before it found the solution! :P

**Comment by Andrew1431** [comment]
https://streamable.com/t6jtvl

boom! Done! it works, can grab any possible key configuration based on those 2 menus.

I got so much UX improvements I want to make to it, but for now it is functional :P

**Comment by atlesque** [comment]
Nice job Andrew!

I agree the key input speed is a good candidate for optimization.

Maybe also test on higher difficulties, to see if it's easy to distinguish the prongs on the inner layers (e.g. layer 4), because they are transparent in-game and I've found it's not so easy to see them.

When you output the solution, an improvement could be to filter by layer, so it's easier to input (useful for higher difficulties).

I'll try to review it later or over the weekend.

**Comment by Andrew1431** [comment]
Agreed to all of the above, I actually put a little disclaimer that this has many UX improvements on it's way :P and yeah to filter layer by layer for sure, i was struggling to follow along when using it myself :P I did test it out on master and it's pretty good, though the solver takes like 1.5s-2s lolz need to clean it up for sure

But in terms of MVP it's definitely there!

**Comment by Andrew1431** [comment]
Added filter-by-layer!

**Comment by Andrew1431** [comment]
Okay, I have put up my final fix, HDPI scaling for mobile, looks much crisper now on mobile. Scaling was odd, had to use it in a few different places and with a few odd modifications. Not exactly sure of the reason for this. 

But it works great now and I tested on DPR's 1, 2, 3, 4, 5, 6, 7, 8 all of which work! 

I am totally satisfied with it now, and have been using it a ton personally to crack the master locks! :) 

I also see you're at the (second) top of the SEO for "starfield digipick solver" so pretty pumped to have this thing go live. 

The first result is some site that has you type in each prong :P I'm sure folks will be pleased with this!
