### ISSUE TITLE
Invalid Key Hint Feedback for Unsolvable Puzzles

### ISSUE THREAD

**Issue by atlesque** [atlesque/starfield-digipick-solver#14]
The following is a valid puzzle from the game:
![image](https://github.com/atlesque/starfield-digipick-solver/assets/44317804/bd1da1b6-000d-4168-bbc1-48b45dcc6ae2)

When I enter it, it says it's unsolvable:
![image](https://github.com/atlesque/starfield-digipick-solver/assets/44317804/349f3bdc-1ca5-45c4-a6ca-3de4029f846a)

I'm on main branch, normally the linter commit was reverted on this one.

**Comment by Andrew1431** [comment]
Key input can be a bit tough, still trying to enhance that, but your first prong is entered incorrectly! :( Though, maybe we could add some feedback that is a warning that the key doesn't fit anywhere in the puzzle?

**Comment by atlesque** [comment]
Oh, shoot, you're right! It's not to easy sometimes with the gaps and mirroring. Adding feedback is a good idea!
