### ISSUE TITLE
Persist state on reload

### ISSUE THREAD

**Issue by atlesque** [atlesque/starfield-digipick-solver#3]
Persist state on reload so an accidental refresh doesn't reset the state.

Especially useful on mobile, where accidental top-to-bottom swipe reloads the page.

**Comment by Andrew1431** [comment]
Nice, I moved all my auto-solver into a context so this would be very simple for the auto-solver portion!

**Comment by Andrew1431** [comment]
Implemented in auto solver 👌

**Comment by atlesque** [comment]
Okay great, I'll have a look. In the future, if possible, please create a seperate PR per issue for easy tracking, thanks 🙏
