### ISSUE TITLE
Add PWA support

### ISSUE THREAD

**Issue by atlesque** [atlesque/starfield-digipick-solver#4]
Add progressive web app support to allow the site to be used in offline mode and also used as a mobile application.

**Comment by Andrew1431** [comment]
Have you started this? I did an initial implementation and am happy to get this working today :) I want to use the app offline! :D

**Comment by atlesque** [comment]
I've assigned you to it. All yours 🙌

**Comment by atlesque** [comment]
Limited to app use for now. Offline use we can implement later.
