### ISSUE TITLE
Github Actions Autodeploy Master

### ISSUE THREAD

**Issue by Andrew1431** [atlesque/starfield-digipick-solver#9]
We should add a github actions script to auto-deploy our latest master branch to your site! 

Have you ever used GHA? They're pretty awesome.

**Comment by atlesque** [comment]
I'm using Cloudflare Pages for deployment, it's linked to the main branch, so no need for GHA 😊

**Comment by Andrew1431** [comment]
Oh awesome :) Thanks!!
